### ISSUE TITLE
Errori schema dati "Consultazione Adeguamento Per Ricongiunzione API"

### ISSUE THREAD

**Issue by mauropratesi** [INPS-it/NDC#1]
Sono stati individuati due errori [1) e 2)] riguardo il seguente [schema dati](https://www.schema.gov.it/semantic-assets/details?uri=https%3A%2F%2Fw3id.org%2Fitalia%2Fschemas%2Fpratica-ricongiuzione%2Flatest%2Fpratica-ricongiuzione.oas3.yaml) presente a Catalogo.
## Comportamento atteso
1) Cliccando sul tasto "Vai al sorgente" l'utente deve essere reindirizzato al repository dell'asset semantico.
2) L'utente, una volta che accede alla scheda dello schema dati, visualizza lo Swagger.

## Comportamento attuale
1) Viene aperta una pagina di errore.
<img width="947" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/157471028/f00136b8-d8c0-4da4-8be5-c4f7d0f0f3ef">

2) Viene mostrato il seguente errore.
<img width="629" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/157471028/7ac91f75-b89c-401e-98ba-ce57d5268e53">

Il problema è che nel TTL gli URL sono sbagliati (manca la 'N', ricongiuzione):
[https://github.com/INPS-it/NDC/blob/d8f24804e82ddcd693edbb2adad53c07afa5c87b/assets/schemas/pratica-ricongiunzione/latest/index.ttl](https://urldefense.com/v3/__https:/github.com/INPS-it/NDC/blob/d8f24804e82ddcd693edbb2adad53c07afa5c87b/assets/schemas/pratica-ricongiunzione/latest/index.ttl__;!!OrxsNty6D4my!-L66BPsvrixgKniksJAWPRPS-DeR4v30nTCwp_aljCpUxxf1LhK0cpP2OHFW0u15es5tU-wPWtsgDXhNRfZ_gvpYOOpUyg$)
dcat:accessURL <[https://github.com/INPS-it/NDC/tree/main/assets/schemas/pratica-ricongiuzione/latest>](https://urldefense.com/v3/__https:/github.com/INPS-it/NDC/tree/main/assets/schemas/pratica-ricongiuzione/latest*3E__;JQ!!OrxsNty6D4my!-L66BPsvrixgKniksJAWPRPS-DeR4v30nTCwp_aljCpUxxf1LhK0cpP2OHFW0u15es5tU-wPWtsgDXhNRfZ_gvrwVwoz7A$) ;
dcat:distribution <[https://w3id.org/italia/schemas/pratica-ricongiuzione/latest/pratica-ricongiuzione.oas3.yaml>](https://urldefense.com/v3/__https:/w3id.org/italia/schemas/pratica-ricongiuzione/latest/pratica-ricongiuzione.oas3.yaml*3E__;JQ!!OrxsNty6D4my!-L66BPsvrixgKniksJAWPRPS-DeR4v30nTCwp_aljCpUxxf1LhK0cpP2OHFW0u15es5tU-wPWtsgDXhNRfZ_gvpZhlL8bg$) ;
dcat:downloadURL <[https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/pratica-ricongiuzione/latest/pratica-ricongiuzione.oas3.yaml>](https://urldefense.com/v3/__https:/raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/pratica-ricongiuzione/latest/pratica-ricongiuzione.oas3.yaml*3E__;JQ!!OrxsNty6D4my!-L66BPsvrixgKniksJAWPRPS-DeR4v30nTCwp_aljCpUxxf1LhK0cpP2OHFW0u15es5tU-wPWtsgDXhNRfZ_gvpQaxB9Cg$) ;

cc: @bruno-marino;@clou-dia; @AgostinoPurificato

**Comment by bruno-marino** [comment]
Sono stati corretti gli url e i nomi dei file sbagliati. [aa191d5](https://github.com/INPS-it/NDC/commit/aa191d5125487b04487107468b55e2df722499df) [abe15dc](https://github.com/INPS-it/NDC/commit/abe15dc9044b8200b1c6eb04f59accaf8b6510d5)
