### ISSUE TITLE
Schema dati non raggiungibile da schema.gov.it. e titolare errato

### ISSUE THREAD

**Issue by Clou-dia** [INPS-it/NDC#2]
Sul catalogo schema.gov.it diverse risorse schemi dati, non sono raggiungibili.

Ad esempio:
https://schema.gov.it/semantic-assets/details?uri=https%3A%2F%2Fw3id.org%2Fitalia%2Fschemas%2Fstato-di-accolta-domanda-naspi%2Flatest%2Fstato-di-accolta-domanda-naspi.oas3.yaml

qui il vostro asset
assets/schemas/stato-di-accolta-domanda-naspi/latest/index.ttl

**inoltre il titolare (rightsHolder) è Inail** il che è errato in un repository INPS

@bruno-marino

**Comment by bruno-marino** [comment]
Verifichiamo e correggiamo
@marco-agostini

**Comment by Clou-dia** [comment]
appena effettuata la verifica/modifica dovreste avvertirci per far ripartire l'harvester in produzione. L'harvesting in test è attivo e si rigenera ogni due ore, quindi potete effettuare i test direttamente li. 
Mi pare che il problema su Naspi sia risolto, non saprei se c'è altro
 https://ndc-test.apps.cloudpub.testedev.istat.it/semantic-assets/details?uri=https%3A%2F%2Fw3id.org%2Fitalia%2Fschemas%2Fprestazione-naspi%2Flatest%2Fprestazione-naspi.oas3.yaml

**Comment by bruno-marino** [comment]
@Clou-dia abbiamo risolto.
